import type { SVGProps } from 'react'
import {
  AgentSectionIcon,
  AppearanceSectionIcon,
  AppshotsSectionIcon,
  BrowserUseSectionIcon,
  ChronicleSectionIcon,
  CloudSettingsSectionIcon,
  CodexMicroSectionIcon,
  ComputerUseSectionIcon,
  ConnectionsSectionIcon,
  DataControlsSectionIcon,
  DebugSectionIcon,
  GeneralSettingsSectionIcon,
  GitSettingsSectionIcon,
  HooksSettingsSectionIcon,
  ImportSectionIcon,
  KeyboardShortcutsSectionIcon,
  LocalEnvironmentsSectionIcon,
  McpSettingsSectionIcon,
  PersonalizationSectionIcon,
  PetsSectionIcon,
  PluginsSettingsSectionIcon,
  ProfileSectionIcon,
  SkillsSettingsSectionIcon,
  UsageSectionIcon,
  VoiceSectionIcon,
  WorktreesSectionIcon
} from './sectionIcons'

/** slug → 图标（Codex `use-visible-settings-sections` 里的 `dt` 表，29 个 slug 共用 26 个组件） */
export const SETTINGS_SECTION_ICONS: Record<
  string,
  (props: SVGProps<SVGSVGElement>) => React.JSX.Element
> = {
  'general-settings': GeneralSettingsSectionIcon,
  import: ImportSectionIcon,
  profile: ProfileSectionIcon,
  'codex-micro': CodexMicroSectionIcon,
  appshots: AppshotsSectionIcon,
  appearance: AppearanceSectionIcon,
  voice: VoiceSectionIcon,
  pets: PetsSectionIcon,
  agent: AgentSectionIcon,
  'git-settings': GitSettingsSectionIcon,
  'data-controls': DataControlsSectionIcon,
  'code-review': AgentSectionIcon,
  'cloud-settings': CloudSettingsSectionIcon,
  'cloud-environments': CloudSettingsSectionIcon,
  personalization: PersonalizationSectionIcon,
  usage: UsageSectionIcon,
  debug: DebugSectionIcon,
  'computer-use': ComputerUseSectionIcon,
  worktrees: WorktreesSectionIcon,
  'mcp-settings': McpSettingsSectionIcon,
  'hooks-settings': HooksSettingsSectionIcon,
  connections: ConnectionsSectionIcon,
  'plugins-settings': PluginsSettingsSectionIcon,
  'skills-settings': SkillsSettingsSectionIcon,
  'keyboard-shortcuts': KeyboardShortcutsSectionIcon,
  chronicle: ChronicleSectionIcon,
  'browser-use': BrowserUseSectionIcon,
  'local-environments': LocalEnvironmentsSectionIcon,
  environments: LocalEnvironmentsSectionIcon
}
